/**
 * Export Utilities — Office Kit Integration
 * Generate wellness reports for export
 */

import { exportUserData } from '../lib/db';

/**
 * Export user data as JSON file
 */
export async function exportAsJSON(userId: string): Promise<void> {
  const data = await exportUserData(userId);
  const blob = new Blob([data], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pranaai-wellness-report-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  console.log('[Export] JSON report downloaded');
}

/**
 * Export user data as CSV file
 */
export async function exportAsCSV(userId: string): Promise<void> {
  const data = JSON.parse(await exportUserData(userId));

  // Journal CSV
  const journalHeaders = ['Date', 'Mood', 'Text', 'Sentiment Score', 'Tags'];
  const journalRows = data.journal.map((e: { timestamp: number; mood: string; text: string; sentimentScore: number; tags: string[] }) => [
    new Date(e.timestamp).toISOString(),
    e.mood,
    `"${e.text.replace(/"/g, '""')}"`,
    e.sentimentScore.toFixed(2),
    e.tags.join('; '),
  ]);

  const journalCSV = [journalHeaders.join(','), ...journalRows.map((r: string[]) => r.join(','))].join('\n');

  // Breathing CSV
  const breathingHeaders = ['Date', 'Pattern', 'Duration (sec)', 'Cycles'];
  const breathingRows = data.breathing.map((s: { timestamp: number; pattern: { name: string }; duration: number; completedCycles: number }) => [
    new Date(s.timestamp).toISOString(),
    s.pattern.name,
    s.duration,
    s.completedCycles,
  ]);

  const breathingCSV = [breathingHeaders.join(','), ...breathingRows.map((r: string[]) => r.join(','))].join('\n');

  // Combine
  const combined = `JOURNAL ENTRIES\n${journalCSV}\n\nBREATHING SESSIONS\n${breathingCSV}`;

  const blob = new Blob([combined], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pranaai-wellness-data-${new Date().toISOString().split('T')[0]}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  console.log('[Export] CSV report downloaded');
}

/**
 * Generate text summary of wellness data
 */
export async function generateTextSummary(userId: string): Promise<string> {
  const data = JSON.parse(await exportUserData(userId));
  const { stats, journal, breathing } = data;

  const summary = `
╔══════════════════════════════════════════════════════════╗
║           PRANAAI WELLNESS REPORT                        ║
║           Generated: ${new Date().toLocaleDateString()}                    ║
╚══════════════════════════════════════════════════════════╝

📊 OVERVIEW
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Journal Entries: ${stats.journalEntries}
• Breathing Sessions: ${stats.breathingSessions}
• Chat Messages: ${stats.chatMessages}

📝 MOOD TRENDS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${journal.slice(0, 5).map((e: { mood: string; timestamp: number; text: string }) =>
    `• ${new Date(e.timestamp).toLocaleDateString()} — ${e.mood.toUpperCase()}: "${e.text.slice(0, 60)}..."`
  ).join('\n') || 'No journal entries yet'}

🫁 BREATHING SESSIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${breathing.slice(0, 5).map((s: { pattern: { name: string }; duration: number; completedCycles: number; timestamp: number }) =>
    `• ${new Date(s.timestamp).toLocaleDateString()} — ${s.pattern.name}: ${Math.round(s.duration / 60)}min, ${s.completedCycles} cycles`
  ).join('\n') || 'No breathing sessions yet'}

💡 RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${generateRecommendations(journal, breathing)}

═══════════════════════════════════════════════════════════
Generated by PranaAI — On-Device Wellness Companion
All data processed locally. Zero cloud calls.
═══════════════════════════════════════════════════════════
`;

  return summary.trim();
}

function generateRecommendations(journal: Array<{ mood: string }>, breathing: Array<{ duration: number }>): string {
  const recommendations: string[] = [];

  // Analyze mood patterns
  const moodCounts: Record<string, number> = {};
  journal.forEach((e: { mood: string }) => {
    moodCounts[e.mood] = (moodCounts[e.mood] || 0) + 1;
  });

  const dominantMood = Object.entries(moodCounts).sort((a, b) => b[1] - a[1])[0];

  if (dominantMood) {
    if (dominantMood[0] === 'anxious' || dominantMood[0] === 'stressed') {
      recommendations.push('• Try the 4-7-8 breathing pattern to reduce anxiety');
      recommendations.push('• Practice box breathing (4-4-4-4) for focus');
    } else if (dominantMood[0] === 'sad' || dominantMood[0] === 'depressed') {
      recommendations.push('• Consider talking to someone you trust');
      recommendations.push('• Try energizing breathing patterns');
    } else if (dominantMood[0] === 'happy' || dominantMood[0] === 'calm') {
      recommendations.push('• Great mood streak! Keep up the breathing practice');
    }
  }

  // Analyze breathing consistency
  if (breathing.length < 5) {
    recommendations.push('• Aim for at least 5 breathing sessions per week');
  }

  if (breathing.some((s: { duration: number }) => s.duration < 60)) {
    recommendations.push('• Try extending sessions to 2-3 minutes for deeper benefits');
  }

  if (recommendations.length === 0) {
    recommendations.push('• Keep journaling and breathing regularly!');
    recommendations.push('• Your data shows a balanced wellness routine');
  }

  return recommendations.join('\n');
}

/**
 * Share report via Web Share API (mobile)
 */
export async function shareReport(userId: string): Promise<void> {
  const summary = await generateTextSummary(userId);

  if (navigator.share) {
    try {
      await navigator.share({
        title: 'PranaAI Wellness Report',
        text: summary,
      });
      console.log('[Export] Report shared via Web Share API');
    } catch (err) {
      console.log('[Export] Share cancelled or failed:', err);
    }
  } else {
    // Fallback: copy to clipboard
    await navigator.clipboard.writeText(summary);
    console.log('[Export] Report copied to clipboard');
  }
}
